
# TensorFlow 2 Exercises for Basic Tensor Manipulation

This notebook provides a set of exercises designed to familiarize you with the basics of tensor manipulation in TensorFlow 2,
which is essential for handling Large Language Models (LLMs).

## Contents
1. Tensor Basics
2. Tensor Operations
3. Manipulating Tensor Shapes
4. Indexing and Slicing
5. Broadcasting
6. Gradients and Differentiation
7. Simple Neural Network Components
8. Data Loading and Preprocessing

Each section will include a brief explanation followed by practical exercises.



## 1. Tensor Basics

**Objective**: Understand how to create tensors, and learn about their types and shapes.

**Exercises**:
1. Create a scalar tensor (0-D tensor) with a specific value.
2. Create a 1-D tensor (vector) with 5 elements.
3. Create a 2-D tensor (matrix) of shape (3, 3).
4. Find the data type (`dtype`) of the tensors created above.
5. Convert a numpy array to a TensorFlow tensor.


prompt: explain what a tensor is and what the purpose of it is compared to a matrix or array

A tensor is a multidimensional array, similar to a matrix or an array in other programming languages. However, tensors are specifically designed for use in TensorFlow and other deep learning frameworks.

**Key Differences:**

1. **Dimensions**: Tensors can have any number of dimensions, while matrices are typically limited to two dimensions.
2. **Data Types**: Tensors support a wider range of data types, including floating-point numbers, integers, strings, and booleans.
3. **Operations**: TensorFlow provides a rich set of operations specifically designed for tensors, including matrix multiplication, convolutions, and other operations commonly used in deep learning.
4. **Gradient Computation**: Tensors are designed to be used with TensorFlow's automatic differentiation capabilities, which allow for efficient computation of gradients for training deep learning models.

**Purpose:**

Tensors are used in TensorFlow to represent various data structures, such as input data, model parameters, and intermediate calculations. They are essential for building and training deep learning models, as they enable efficient manipulation and processing of large amounts of data.

In [2]:
# prompt: creaTE A SCALAR TENSOR 0-D TENSOR WITH A SPECIFIC VALUE

import tensorflow as tf

# Create a scalar tensor with value 10
scalar_tensor = tf.constant(10)

# Print the scalar tensor
print(scalar_tensor)


tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
d1_tensor = tf.constant([1, 2, 3, 4, 5])
print(d1_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
d2_tensor = tf.constant([[1, 2, 3], [4, 5, 6], [10, 4, 9]])
print(d2_tensor)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [10  4  9]], shape=(3, 3), dtype=int32)


In [ ]:
scalar_tensor.dtype
d1_tensor.dtype
d2_tensor.dtype

tf.int32

In [ ]:
# prompt: create a numpy array and convert to tensor

import numpy as np

# Create a numpy array
numpy_array = np.array([1, 2, 3, 4, 5])

# Convert the numpy array to a TensorFlow tensor
tensor = tf.constant(numpy_array)

# Print the tensor
print(tensor)


tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)



## 2. Tensor Operations

**Objective**: Perform basic arithmetic operations and learn some advanced operations.

**Exercises**:
1. Add, subtract, multiply, and divide two tensors.
2. Compute the mean and standard deviation of a tensor.
3. Apply a non-linear activation function (like ReLU) to a tensor.
4. Perform matrix multiplication between two 2-D tensors.


In [ ]:
d2_tensor_1 = tf.constant([[1, 4, 2], [4, 5, 6], [7, 4, 9]])

In [ ]:
d2_tensor + d2_tensor_1, d2_tensor - d2_tensor_1, d2_tensor * d2_tensor_1, d2_tensor / d2_tensor_1

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 2,  6,  5],
        [ 8, 10, 12],
        [17,  8, 18]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 0, -2,  1],
        [ 0,  0,  0],
        [ 3,  0,  0]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 1,  8,  6],
        [16, 25, 36],
        [70, 16, 81]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=float64, numpy=
 array([[1.        , 0.5       , 1.5       ],
        [1.        , 1.        , 1.        ],
        [1.42857143, 1.        , 1.        ]])>)

In [ ]:
np.mean(d2_tensor), np.std(d2_tensor)

(4.888888888888889, 2.8458329944145997)

In [ ]:
# prompt: apply ReLU to d2_tensor

tf.nn.relu(d2_tensor)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10,  4,  9]], dtype=int32)>

In [ ]:
# prompt: apply matrix multiplication between d2_tensor and d2_tensor_1

tf.matmul(d2_tensor, d2_tensor_1)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  26,  41],
       [ 66,  65,  92],
       [ 89,  96, 125]], dtype=int32)>


## 3. Manipulating Tensor Shapes

**Objective**: Learn how to reshape and transpose tensors.

**Exercises**:
1. Create a tensor of shape (4, 4), then reshape it to (2, 8).
2. Transpose a 2-D tensor.
3. Flatten a 3-D tensor to a 1-D tensor.


In [3]:
d4_tensor = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
d4_tensor

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)>

In [4]:
d4_tensor_28 = tf.reshape(d4_tensor, (2, 8))
d4_tensor_28

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]], dtype=int32)>

In [5]:
d4_tensor_transpose = tf.transpose(d4_tensor)
d4_tensor_transpose

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]], dtype=int32)>

In [6]:
d4_tensor_flatten = tf.reshape(d4_tensor, (-1))
d4_tensor_flatten

<tf.Tensor: shape=(16,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int32)>


## 4. Indexing and Slicing

**Objective**: Access specific elements or slices of a tensor.

**Exercises**:
1. Extract a specific element from a tensor.
2. Slice a portion of a tensor.
3. Use boolean tensor indexing to filter elements.


In [7]:
d4_tensor[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [8]:
# prompt: slice a portion of a tensor

d4_tensor[:2, 2:]


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [7, 8]], dtype=int32)>

In [9]:
d4_tensor_bool = d4_tensor[d4_tensor > 10]
d4_tensor_bool

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([11, 12, 13, 14, 15, 16], dtype=int32)>


## 5. Broadcasting

**Objective**: Understand and apply broadcasting rules in tensor operations.

**Exercises**:
1. Perform an element-wise addition between tensors of different shapes.
2. Broadcast a smaller tensor to match the shape of a larger tensor in an operation.



## 6. Gradients and Differentiation

**Objective**: Basic introduction to automatic differentiation.

**Exercises**:
1. Use `tf.GradientTape` to compute derivatives.
2. Find the gradient of a simple function with respect to one of its inputs.



## 7. Data Loading and Preprocessing

**Objective**: Use `tf.data` for efficient data handling.

**Exercises**:
1. Create a simple dataset using `tf.data.Dataset`.
2. Apply a transformation (like mapping) to the dataset.
3. Batch and shuffle the dataset.
